#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

banner "Cloudflare Workers AI 設定（階段 8 產圖用）"

# ── Stage 1：帳號 ──────────────────────────────────────────────────────────
stage "Cloudflare 帳號（免費方案即可，不用綁卡）"
say "產圖走 Cloudflare Workers AI 免費層（每天 10,000 neurons）。"
open_url "https://dash.cloudflare.com/sign-up"
step "已有帳號就直接登入；沒有就註冊（Email + 密碼，不需要加網域、不需要信用卡）。"
step "完成 Email 驗證後回到 dashboard 首頁。"
pause "登入完成後按 Enter"

# ── Stage 2：Account ID ────────────────────────────────────────────────────
stage "取得 CLOUDFLARE_ACCOUNT_ID"
say "Account ID 是一串 32 字元的十六進位值（不是機密，但每個 API 呼叫都要帶）。"
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "左側選單點「Compute (Workers)」或「Workers & Pages」。"
step "右側欄位找「Account ID」，點 Copy。"
note "找不到的話：看瀏覽器網址列 dash.cloudflare.com/【這一段】/... 就是 Account ID。"
ask CLOUDFLARE_ACCOUNT_ID "貼上 Account ID："
write_env CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"

# ── Stage 3：API Token ─────────────────────────────────────────────────────
stage "建立 Workers AI API Token"
say "用官方的 Workers AI 模板建 token（權限最小化，只能呼叫 AI 模型）。"
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "點「Create Token」。"
step "在模板清單找「Workers AI」→ 點「Use template」。"
note "找不到模板的話：Create Custom Token → Permissions 選 Account / Workers AI / Edit。"
step "Account Resources 保持你的帳號 → Continue to summary → Create Token。"
step "複製畫面上顯示的 token（只會顯示這一次！）。"
ask_secret CLOUDFLARE_API_TOKEN "貼上 API Token（輸入時不會顯示）："
write_env CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"

# ── Stage 4：驗證 + GitHub secrets ─────────────────────────────────────────
stage "驗證：實打一張 flux-1-schnell 測試圖"
say "先驗 token 有效，再真的產一張圖（消耗約 58 neurons，額度 10,000/天）。"

VERIFY_STATUS=$(curl -s -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
  "https://api.cloudflare.com/client/v4/user/tokens/verify" | grep -o '"status":"[a-z]*"' || true)
if [[ "$VERIFY_STATUS" == '"status":"active"' ]]; then
  printf '  %s✓%s token 驗證通過（active）\n' "$GREEN" "$RESET"
else
  warn "token 驗證失敗（$VERIFY_STATUS）——請確認 token 貼對了；可 Ctrl-C 後重跑本精靈"
  pause "仍要繼續嘗試產圖請按 Enter"
fi

say "產圖中（數秒）…"
HTTP_CODE=$(curl -s -o /tmp/cf-flux-test.json -w "%{http_code}" -X POST \
  "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/ai/run/@cf/black-forest-labs/flux-1-schnell" \
  -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" -H "Content-Type: application/json" \
  -d '{"prompt":"anime style illustration of a cozy Kyoto street at golden hour, no text","steps":4}')

if [[ "$HTTP_CODE" == "200" ]] && python3 - <<'PY'
import base64, json, sys
body = json.load(open("/tmp/cf-flux-test.json"))
image = body.get("result", {}).get("image")
sys.exit(0 if image and bool(base64.b64decode(image[:80] + "=" * 3, validate=False)) else 1)
PY
then
  python3 -c "import base64,json; open('/tmp/cf-flux-test.jpg','wb').write(base64.b64decode(json.load(open('/tmp/cf-flux-test.json'))['result']['image']))"
  printf '  %s✓%s 產圖成功 → /tmp/cf-flux-test.jpg\n' "$GREEN" "$RESET"
  open_url "file:///tmp/cf-flux-test.jpg"
else
  warn "產圖失敗（HTTP $HTTP_CODE）——回應存在 /tmp/cf-flux-test.json，把內容貼給 Claude 排查"
  pause "按 Enter 繼續（GitHub secrets 仍會設定）"
fi

say "把兩個值設成 GitHub secrets（階段 8 的 CI 部署會用）…"
set_secret CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
set_secret CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"

finish
