#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

banner "AI Companion API — 階段 0 帳號與金鑰設定（Cloud Run + Neon + Gemini + Groq）"

# ── Stage 1 · 前置檢查：gh CLI 與 GitHub repo ─────────────────────────────
stage "前置檢查 — gh CLI 與 GitHub repo"
say "CI 部署需要一個 GitHub repo，而這支 wizard 會用 gh CLI 幫你寫入 repo secrets。"
if ! command -v gh >/dev/null 2>&1; then
  warn "找不到 gh CLI。請先安裝：brew install gh"
  pause "安裝完成後按 Enter 繼續"
fi
if ! gh auth status >/dev/null 2>&1; then
  say "gh 尚未登入，執行 gh auth login（會開瀏覽器）…"
  gh auth login || warn "gh 登入失敗——secrets 之後要手動設"
fi
if ! git remote get-url origin >/dev/null 2>&1; then
  say "這個 repo 還沒有 GitHub remote。"
  if confirm "要現在建立私有 repo ai-companion-api 並推上去嗎？"; then
    if gh repo create ai-companion-api --private --source . --push; then
      say "✓ repo 建立完成"
    else
      warn "建立失敗——請手動 gh repo create 後重跑本 wizard"
    fi
  else
    warn "沒有 remote 的話，最後的自動部署會做不了"
  fi
else
  say "✓ 已有 remote：$(git remote get-url origin)"
fi

# ── Stage 2 · GCP 專案與計費 ──────────────────────────────────────────────
stage "GCP — 建立專案並啟用計費"
say "Cloud Run 需要一個 GCP 專案，且必須綁信用卡啟用計費（免費層額度內不會扣款：每月 200 萬請求）。"
open_url "https://console.cloud.google.com/projectcreate"
step "登入 Google 帳號後建立新專案，名稱建議 ai-companion-api。"
step "建立後記下「專案 ID」（Project ID，不是名稱；通常長得像 ai-companion-api-123456）。"
ask GCP_PROJECT_ID "貼上專案 ID："
write_env GCP_PROJECT_ID "$GCP_PROJECT_ID"
set_secret GCP_PROJECT_ID "$GCP_PROJECT_ID"   # CI 的 deploy.yml 會用
say ""
say "接著啟用計費（第一次會要你綁信用卡）："
open_url "https://console.cloud.google.com/billing/linkedaccount?project=${GCP_PROJECT_ID}"
step "依畫面指示建立帳單帳戶並連結到這個專案。"
pause "計費啟用完成後按 Enter"

# ── Stage 3 · 啟用 Cloud Run 相關 API ────────────────────────────────────
stage "GCP — 啟用 Cloud Run / Cloud Build / Artifact Registry API"
say "CI 用「gcloud run deploy --source」部署，需要這三個 API。"
open_url "https://console.cloud.google.com/flows/enableapi?apiid=run.googleapis.com,cloudbuild.googleapis.com,artifactregistry.googleapis.com&project=${GCP_PROJECT_ID}"
step "頁面會列出三個 API，按「啟用」（Enable）並等它跑完。"
pause "三個 API 都啟用後按 Enter"

# ── Stage 4 · Service Account 與 JSON 金鑰 ───────────────────────────────
stage "GCP — 建立部署用 Service Account 金鑰"
say "GitHub Actions 用這把金鑰代表你部署。"
open_url "https://console.cloud.google.com/iam-admin/serviceaccounts/create?project=${GCP_PROJECT_ID}"
step "服務帳戶名稱填 github-deployer，按「建立並繼續」。"
step "授予這些角色（一個一個加）："
say "    - Cloud Run 管理員（Cloud Run Admin）"
say "    - 服務帳戶使用者（Service Account User）"
say "    - Cloud Build 編輯者（Cloud Build Editor）"
say "    - Storage 管理員（Storage Admin）"
say "    - Artifact Registry 管理員（Artifact Registry Administrator）"
step "完成建立後，點進該服務帳戶 → 金鑰（Keys）→ 新增金鑰 → JSON → 會下載一個 .json 檔。"
ask GCP_SA_KEY_FILE "貼上下載的 JSON 檔完整路徑（例如 ~/Downloads/xxx.json）："
case "$GCP_SA_KEY_FILE" in "~"*) GCP_SA_KEY_FILE="${HOME}${GCP_SA_KEY_FILE#\~}";; esac
if [[ -f "$GCP_SA_KEY_FILE" ]]; then
  set_secret GCP_SA_KEY "$(cat "$GCP_SA_KEY_FILE")"
  if confirm "金鑰已存進 GitHub secret，要刪除本機的 JSON 檔嗎（建議，避免外洩）？"; then
    rm "$GCP_SA_KEY_FILE" && say "✓ 已刪除 $GCP_SA_KEY_FILE"
  fi
else
  warn "找不到檔案 $GCP_SA_KEY_FILE — 請稍後手動：gh secret set GCP_SA_KEY < 路徑.json"
  SKIPPED+=("GitHub secret GCP_SA_KEY（gh secret set GCP_SA_KEY < 金鑰.json）")
fi

# ── Stage 5 · Neon Postgres ──────────────────────────────────────────────
stage "Neon — 免費 Postgres（取代 SQLite）"
say "免費層 0.5GB，閒置只是秒級休眠、不會被停用。"
open_url "https://console.neon.tech/signup"
step "用 GitHub 或 Google 帳號註冊。"
step "建立專案：名稱 ai-companion-api，區域選 Asia Pacific（Singapore 或 Tokyo）。"
step "建立後在 Dashboard 的「Connect / Connection string」複製 postgresql://... 連線字串。"
ask_secret DATABASE_URL "貼上連線字串（輸入時不會顯示）："
write_env DATABASE_URL "$DATABASE_URL"
note "階段 0 還用不到 DB；階段 6 儲存層才會接上。"

# ── Stage 6 · Gemini API key ─────────────────────────────────────────────
stage "Gemini — AI Studio API key（推理主力 + 產圖）"
say "免費層 Flash 系列約 1,500 次/天，同一把 key 之後也拿來產圖。"
open_url "https://aistudio.google.com/apikey"
step "登入 Google 帳號 → Create API key → 選剛才的 GCP 專案（或讓它自動建）→ 複製 key。"
ask_secret GEMINI_API_KEY "貼上 Gemini API key："
write_env GEMINI_API_KEY "$GEMINI_API_KEY"

# ── Stage 7 · Groq API key ───────────────────────────────────────────────
stage "Groq — API key（輕量判讀分流）"
say "免費層 30 次/分、14,400 次/天，免信用卡。"
open_url "https://console.groq.com/keys"
step "註冊/登入 → Create API Key → 命名 ai-companion-api → 複製 key（只顯示一次）。"
ask_secret GROQ_API_KEY "貼上 Groq API key："
write_env GROQ_API_KEY "$GROQ_API_KEY"

# ── Stage 8 · data/ai_partner.json（可跳過）──────────────────────────────
stage "資料缺口 — data/ai_partner.json"
say "ai-partner 端點目前用佔位資料。真實內容要打原始服務（公司內網）取回。"
if confirm "你現在連得到原始 kkday-b2c-api 服務嗎？"; then
  ask SOURCE_API_BASE "貼上原始服務的 base URL（例如 https://xxx.kkday.com）："
  say "抓取中：GET ${SOURCE_API_BASE}/api/v3/companion/ai-partner …"
  if curl -sf "${SOURCE_API_BASE}/api/v3/companion/ai-partner" \
      | python3 -c 'import json,sys; body=json.load(sys.stdin); json.dump(body["data"], open("data/ai_partner.json","w"), ensure_ascii=False, indent=2)'; then
    say "✓ 已寫入 data/ai_partner.json（取回應的 data 欄位原樣存檔）"
  else
    warn "抓取失敗——之後手動 curl 存檔即可"
    SKIPPED+=("data/ai_partner.json：curl 原始服務 /api/v3/companion/ai-partner 的 data 欄位存檔")
  fi
else
  note "跳過。之後拿到再覆蓋 data/ai_partner.json 即可，格式見 docs/source-spec.md 4.1。"
  SKIPPED+=("data/ai_partner.json（目前是佔位資料）")
fi

# ── Stage 9 · 推上 GitHub、部署並驗收 ────────────────────────────────────
stage "部署 — push 觸發 CI，然後驗收"
say "push 到 main 會自動跑測試 + 部署到 Cloud Run（asia-east1）。"
if confirm "現在 git push 觸發部署嗎？"; then
  git push -u origin main || warn "push 失敗——確認 remote 與權限後手動 push"
  say ""
  step "開 GitHub Actions 看部署進度（第一次含 Cloud Build 約 5-10 分鐘）："
  open_url "$(gh repo view --json url -q .url 2>/dev/null || echo https://github.com)/actions"
  step "部署成功後，從 Actions log 末尾或 Cloud Run console 複製服務網址（https://ai-companion-api-xxx.run.app）。"
  ask SERVICE_URL "貼上服務網址："
  write_env SERVICE_URL "$SERVICE_URL"
  say "驗收 /health …"
  if curl -sf "${SERVICE_URL}/health"; then
    say ""; say "✓ /health OK"
  else
    warn "/health 失敗"
  fi
  say "驗收 timeout：/debug/sleep?seconds=45（會等 45 秒，不能被平台切斷）…"
  if curl -sf --max-time 90 "${SERVICE_URL}/debug/sleep?seconds=45"; then
    say ""; say "✓ 45 秒請求存活 — timeout 門檻通過"
  else
    warn "sleep 45s 失敗 — 檢查 Cloud Run timeout 設定"
  fi
  note "冷啟動實測要等閒置 30 分鐘後再打一次 /health 並計時（time curl ${SERVICE_URL}/health）。"
else
  SKIPPED+=("git push 觸發部署 + /health、/debug/sleep 驗收")
fi

finish
